FROM tensorflow/tensorflow:latest-py3

WORKDIR /app

COPY backend/requirements.txt backend/backend.py ./

ENV FLASK_APP=view.py

RUN pip install -r ./requirements.txt
#ENV FLASK_ENV production

EXPOSE 5000

CMD ["gunicorn", "-b", ":5000", "backend:app"]